require"Engine"
Game=class({
	static={
		Initialize=function(self)
			SceneManager:Initialize(require("./Assets/mScene"))
			RenderManager:Initialize()
		end,
		Tick=function(self,delta)
			SceneManager:Tick(delta)
			RenderManager:Tick(delta)
		end,
		Finalize=function(self)
			SceneManager:Finalize()
			RenderManager:Finalize()
		end
	}
})
