return {
    {
        ["name"]="DirectionLight",
        ["uuid"]="0",
        ["parent"]=nil,
        ["components"]=
        {
            ["Light"]=
            {

            },
            ["Transform"]={
                ["position"]={0,0,0},
                ["rotation"]={0,0,0,0},
                ["scale"]={1,1,1},
            }
        }
    },
    {
        ["name"]="Main Camera",
        ["uuid"]="1",
        ["parent"]=nil,
        ["components"]={
            ["Camera"]=
            {
                
            },
            ["Transform"]={
                ["position"]={0,0,-10},
                ["rotation"]={0,0,0,0},
                ["scale"]={1,1,1},
            }
        }
    },
    {
        ["name"]="Cube",
        ["uuid"]="2",
        ["parent"]=nil,
        ["components"]={
            ["Renderer"]=
            {
                ["Material"]="defaultMaterial"
            },
            ["MeshFilter"]=
            {
                ["mesh"]={
                    ["vertices"]={
                        -0.5,-0.5,-0.5,
                        0.5,-0.5,-0.5,
                        0.5,0.5,-0.5,
                    },
                    ["trangles"]={
                        1,2,3
                    }
                }
            },
            ["Transform"]={
                ["position"]={0,0,0},
                ["rotation"]={0,0,0,0},
                ["scale"]={1,1,1},
            }
        }
    }
}