return {
    {
        name="root",
        uuid=0,
        components=
        {
            Light=
            {

            },
            Transform={
                position={0,0,0},
                rotation={0,0,0,0},
                scale={1,1,1},
            }
        }
    },
    {
        name="Main Camera",
        uuid=1,
        parent=0,
        components={
            Camera=
            {
                
            },
            Transform={
                position={0,0,-10},
                rotation={0,0,0,0},
                scale={1,1,1},
            }
        }
    },
    {
        name="Cube",
        uuid=2,
        parent=0,
        components={
            Renderer=
            {
                Material="defaultMaterial"
            },
            MeshFilter=
            {
                mesh={}
            },
            Transform={
                position={0,0,0},
                rotation={0,0,0,0},
                scale={1,1,1},
            }
        }
    }
}